blank_issues_enabled: false
contact_links:
  - name: Questions for Neopilot extensions
    url: https://github.com/orgs/neopilot-ai/discussions/categories/neopilot
    about: Please ask and answer questions about using Neopilot here
